groups:
- name: service.rules
  rules:
  - alert: InstanceDown
    expr: up{job="service.rules"} == 0
    for: 5m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ .instance }} down"
      description: "{{ .instance }} of job {{ .job }} has been down for more than 5 minutes."

#==========CPU==================================================================
  - alert: NodeCPUUsage
    expr: (100 - (irate(node_cpu{mode="idle", job="service.rules"}[5m]) * 100)) > 50
    for: 2m
    labels:
      severity: page
    annotations:
      summary: High CPU usage detected CPU usage is above 75%
# ==============Memory==========================================================
  - alert: NodeSwapUsageSwap
    expr: (((node_memory_SwapTotal-node_memory_SwapFree{job="service.rules"})/node_memory_SwapTotal{job="service.rules"})*100) > 30
    for: 2m 
    labels:
      severity: page
    annotations:
      summary: Swap usage detected Swap usage usage is above 50%
  - alert: NodeMemoryUsageMemFree
    expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached{job="service.rules"})/(node_memory_MemTotal{job=""})*100)) > 30
    for: 2m
    labels:
      severity: page
    annotations:
      summary: High memory usage detected, Memory usage is above 50%
#==============Load=============================================================

  - alert: nodeLoad1
    expr: node_load1{job="service.rules"} > 0.7
    for: 1m
    labels:
      severity: page
    annotations:
      summary: Load
#================Disk space Used ================================================
  - alert: diskSpaceUsed
    expr: (100.0 - 100 * (node_filesystem_avail{job="service.rules"} / node_filesystem_size{job="service.rules"})) > 80
    for: 10m
    labels:
      severity: page
    annotations:
      summary: Disk space userd 80
#=============nodeContrack========================================
  - alert: nodeContrack
    expr: node_nf_conntrack_entries{job="service.rules"} > 200
    for: 10m
    labels:
      severity: page
    annotations:
      summary: nodeContrack
#=============nodeCntextSwitches ========================================
  - alert: nodeCntextSwitches
    expr: irate(node_context_switches{job="service.rules"}[5m]) > 100
    for: 5m
    labels:
      severity: page
    annotations:
      summary: nodeCntextSwitches
#=============Disk Utilization per Device ========================================
  - alert: DiskUtilizationPerDevice
    expr: irate(node_disk_io_time_ms{job="service.rules"}[5m])/10 > 0.2
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskUtilizationPerDevice
#============Disk IOs per Device ========================================
  - alert: DiskIOsPerDeviceRead
    expr: irate(node_disk_reads_completed{job="service.rules"}[5m]) >10
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice

  - alert: DiskIOsPerDeviceWrite
    expr: irate(node_disk_writes_completed{job="service.rules"}[5m]) > 10
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice
#===========Disk Throughput per Device========================================
  - alert: DiskThroughputPerDeviceReads
    expr: irate(node_disk_sectors_read{job="service.rules"}[5m]) * 512 >10000000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice
  - alert: DiskThroughputPerDeviceWrites
    expr: irate(node_disk_sectors_written{job="service.rules"}[5m]) * 512 > 10000000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice
#===========Network Traffic========================================
  - alert: NetworkTrafficReceive
    expr: irate(node_network_receive_bytes{job="service.rules"}[5m])*8 > 5000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: NetworkTrafficReceive
  - alert: NetworkTrafficTransmit
    expr: irate(node_network_transmit_bytes{job="service.rules"}[5m])*8 > 5000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: NetworkTrafficTransmit

#===========Netstat========================================
  - alert: Netstat
    expr: node_netstat_Tcp_CurrEstab{job="service.rules"} > 20
    for: 5m
    labels:
      severity: page
    annotations:
      summary: Netstat

#===========UDP Stats============================
  - alert: UDPStatsInDatagrams
    expr: irate(node_netstat_Udp_InDatagrams{job="service.rules"}[5m]) > 50
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats
  - alert: UDPStatsInErrors
    expr: irate(node_netstat_Udp_InErrors{job="service.rules"}[5m]) > 20
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats
  - alert: UDPStatsOutDatagrams
    expr: irate(node_netstat_Udp_OutDatagrams{job="service.rules"}[5m]) > 50
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats
  - alert: UDPStatsNoPorts
    expr: irate(node_netstat_Udp_NoPorts{job="service.rules"}[5m]) > 20
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats