groups:
- name: service.rules
  rules:
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service {{ $labels.instance }} is down"
      description: "{{ $labels.job }} service at {{ $labels.instance }} has been down for more than 1 minute."

  - alert: HighPostgresConnections
    expr: pg_stat_activity_count > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High PostgreSQL connections ({{ $value }})"
      description: "Database connections are high for instance {{ $labels.instance }}"

  - alert: RedisMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High Redis memory usage ({{ $value }}%)"
      description: "Redis instance {{ $labels.instance }} is using {{ $value }}% of available memory"