# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0cuser_service\"Y\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x11\n\tfull_name\x18\x04 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x9d\x01\n\x0cUserResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08username\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tfull_name\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x05\n\x03_idB\x0b\n\t_usernameB\x08\n\x06_emailB\x0c\n\n_full_name\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t2\xdf\x01\n\x0bUserService\x12I\n\nCreateUser\x12\x1f.user_service.CreateUserRequest\x1a\x1a.user_service.UserResponse\x12@\n\x05Login\x12\x1a.user_service.LoginRequest\x1a\x1b.user_service.LoginResponse\x12\x43\n\x07GetUser\x12\x1c.user_service.GetUserRequest\x1a\x1a.user_service.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=28
  _globals['_CREATEUSERREQUEST']._serialized_end=117
  _globals['_GETUSERREQUEST']._serialized_start=119
  _globals['_GETUSERREQUEST']._serialized_end=147
  _globals['_USERRESPONSE']._serialized_start=150
  _globals['_USERRESPONSE']._serialized_end=307
  _globals['_LOGINREQUEST']._serialized_start=309
  _globals['_LOGINREQUEST']._serialized_end=359
  _globals['_LOGINRESPONSE']._serialized_start=361
  _globals['_LOGINRESPONSE']._serialized_end=398
  _globals['_USERSERVICE']._serialized_start=401
  _globals['_USERSERVICE']._serialized_end=624
# @@protoc_insertion_point(module_scope)
